/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignIndexRouteImport } from './routes/design/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as ExamplesSsrRouteImport } from './routes/examples/ssr'
import { Route as DesignTokensRouteImport } from './routes/design/tokens'
import { Route as DesignScaleRouteImport } from './routes/design/scale'
import { Route as DesignPatternsRouteImport } from './routes/design/patterns'
import { Route as DesignOverviewRouteImport } from './routes/design/overview'
import { Route as DesignComponentsRouteImport } from './routes/design/components'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'
import { Route as ExamplesComponentsTodosRouteImport } from './routes/examples/components/todos'
import { Route as ExamplesComponentsR2UploadRouteImport } from './routes/examples/components/r2-upload'
import { Route as ExamplesComponentsApiKeysRouteImport } from './routes/examples/components/api-keys'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const ExamplesSsrRoute = ExamplesSsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => ExamplesRoute,
} as any)
const DesignTokensRoute = DesignTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DesignRoute,
} as any)
const DesignScaleRoute = DesignScaleRouteImport.update({
  id: '/scale',
  path: '/scale',
  getParentRoute: () => DesignRoute,
} as any)
const DesignPatternsRoute = DesignPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => DesignRoute,
} as any)
const DesignOverviewRoute = DesignOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DesignRoute,
} as any)
const DesignComponentsRoute = DesignComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DesignRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const ExamplesComponentsTodosRoute = ExamplesComponentsTodosRouteImport.update({
  id: '/components/todos',
  path: '/components/todos',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesComponentsR2UploadRoute =
  ExamplesComponentsR2UploadRouteImport.update({
    id: '/components/r2-upload',
    path: '/components/r2-upload',
    getParentRoute: () => ExamplesRoute,
  } as any)
const ExamplesComponentsApiKeysRoute =
  ExamplesComponentsApiKeysRouteImport.update({
    id: '/components/api-keys',
    path: '/components/api-keys',
    getParentRoute: () => ExamplesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/overview': typeof DesignOverviewRoute
  '/design/patterns': typeof DesignPatternsRoute
  '/design/scale': typeof DesignScaleRoute
  '/design/tokens': typeof DesignTokensRoute
  '/examples/ssr': typeof ExamplesSsrRoute
  '/cases/': typeof CasesIndexRoute
  '/design/': typeof DesignIndexRoute
  '/examples/components/api-keys': typeof ExamplesComponentsApiKeysRoute
  '/examples/components/r2-upload': typeof ExamplesComponentsR2UploadRoute
  '/examples/components/todos': typeof ExamplesComponentsTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/overview': typeof DesignOverviewRoute
  '/design/patterns': typeof DesignPatternsRoute
  '/design/scale': typeof DesignScaleRoute
  '/design/tokens': typeof DesignTokensRoute
  '/examples/ssr': typeof ExamplesSsrRoute
  '/cases': typeof CasesIndexRoute
  '/design': typeof DesignIndexRoute
  '/examples/components/api-keys': typeof ExamplesComponentsApiKeysRoute
  '/examples/components/r2-upload': typeof ExamplesComponentsR2UploadRoute
  '/examples/components/todos': typeof ExamplesComponentsTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/overview': typeof DesignOverviewRoute
  '/design/patterns': typeof DesignPatternsRoute
  '/design/scale': typeof DesignScaleRoute
  '/design/tokens': typeof DesignTokensRoute
  '/examples/ssr': typeof ExamplesSsrRoute
  '/cases/': typeof CasesIndexRoute
  '/design/': typeof DesignIndexRoute
  '/examples/components/api-keys': typeof ExamplesComponentsApiKeysRoute
  '/examples/components/r2-upload': typeof ExamplesComponentsR2UploadRoute
  '/examples/components/todos': typeof ExamplesComponentsTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/design'
    | '/examples'
    | '/login'
    | '/cases/$caseId'
    | '/design/components'
    | '/design/overview'
    | '/design/patterns'
    | '/design/scale'
    | '/design/tokens'
    | '/examples/ssr'
    | '/cases/'
    | '/design/'
    | '/examples/components/api-keys'
    | '/examples/components/r2-upload'
    | '/examples/components/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples'
    | '/login'
    | '/cases/$caseId'
    | '/design/components'
    | '/design/overview'
    | '/design/patterns'
    | '/design/scale'
    | '/design/tokens'
    | '/examples/ssr'
    | '/cases'
    | '/design'
    | '/examples/components/api-keys'
    | '/examples/components/r2-upload'
    | '/examples/components/todos'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/design'
    | '/examples'
    | '/login'
    | '/cases/$caseId'
    | '/design/components'
    | '/design/overview'
    | '/design/patterns'
    | '/design/scale'
    | '/design/tokens'
    | '/examples/ssr'
    | '/cases/'
    | '/design/'
    | '/examples/components/api-keys'
    | '/examples/components/r2-upload'
    | '/examples/components/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  DesignRoute: typeof DesignRouteWithChildren
  ExamplesRoute: typeof ExamplesRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof DesignRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/examples/ssr': {
      id: '/examples/ssr'
      path: '/ssr'
      fullPath: '/examples/ssr'
      preLoaderRoute: typeof ExamplesSsrRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/design/tokens': {
      id: '/design/tokens'
      path: '/tokens'
      fullPath: '/design/tokens'
      preLoaderRoute: typeof DesignTokensRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/scale': {
      id: '/design/scale'
      path: '/scale'
      fullPath: '/design/scale'
      preLoaderRoute: typeof DesignScaleRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/patterns': {
      id: '/design/patterns'
      path: '/patterns'
      fullPath: '/design/patterns'
      preLoaderRoute: typeof DesignPatternsRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/overview': {
      id: '/design/overview'
      path: '/overview'
      fullPath: '/design/overview'
      preLoaderRoute: typeof DesignOverviewRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/components': {
      id: '/design/components'
      path: '/components'
      fullPath: '/design/components'
      preLoaderRoute: typeof DesignComponentsRouteImport
      parentRoute: typeof DesignRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/examples/components/todos': {
      id: '/examples/components/todos'
      path: '/components/todos'
      fullPath: '/examples/components/todos'
      preLoaderRoute: typeof ExamplesComponentsTodosRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/components/r2-upload': {
      id: '/examples/components/r2-upload'
      path: '/components/r2-upload'
      fullPath: '/examples/components/r2-upload'
      preLoaderRoute: typeof ExamplesComponentsR2UploadRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/components/api-keys': {
      id: '/examples/components/api-keys'
      path: '/components/api-keys'
      fullPath: '/examples/components/api-keys'
      preLoaderRoute: typeof ExamplesComponentsApiKeysRouteImport
      parentRoute: typeof ExamplesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface DesignRouteChildren {
  DesignComponentsRoute: typeof DesignComponentsRoute
  DesignOverviewRoute: typeof DesignOverviewRoute
  DesignPatternsRoute: typeof DesignPatternsRoute
  DesignScaleRoute: typeof DesignScaleRoute
  DesignTokensRoute: typeof DesignTokensRoute
  DesignIndexRoute: typeof DesignIndexRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignComponentsRoute: DesignComponentsRoute,
  DesignOverviewRoute: DesignOverviewRoute,
  DesignPatternsRoute: DesignPatternsRoute,
  DesignScaleRoute: DesignScaleRoute,
  DesignTokensRoute: DesignTokensRoute,
  DesignIndexRoute: DesignIndexRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

interface ExamplesRouteChildren {
  ExamplesSsrRoute: typeof ExamplesSsrRoute
  ExamplesComponentsApiKeysRoute: typeof ExamplesComponentsApiKeysRoute
  ExamplesComponentsR2UploadRoute: typeof ExamplesComponentsR2UploadRoute
  ExamplesComponentsTodosRoute: typeof ExamplesComponentsTodosRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  ExamplesSsrRoute: ExamplesSsrRoute,
  ExamplesComponentsApiKeysRoute: ExamplesComponentsApiKeysRoute,
  ExamplesComponentsR2UploadRoute: ExamplesComponentsR2UploadRoute,
  ExamplesComponentsTodosRoute: ExamplesComponentsTodosRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  DesignRoute: DesignRouteWithChildren,
  ExamplesRoute: ExamplesRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
