/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesSsrRouteImport } from './routes/examples/ssr'
import { Route as ExamplesComponentsTodosRouteImport } from './routes/examples/components/todos'
import { Route as ExamplesComponentsR2UploadRouteImport } from './routes/examples/components/r2-upload'
import { Route as ExamplesComponentsApiKeysRouteImport } from './routes/examples/components/api-keys'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSsrRoute = ExamplesSsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesComponentsTodosRoute = ExamplesComponentsTodosRouteImport.update({
  id: '/components/todos',
  path: '/components/todos',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesComponentsR2UploadRoute =
  ExamplesComponentsR2UploadRouteImport.update({
    id: '/components/r2-upload',
    path: '/components/r2-upload',
    getParentRoute: () => ExamplesRoute,
  } as any)
const ExamplesComponentsApiKeysRoute =
  ExamplesComponentsApiKeysRouteImport.update({
    id: '/components/api-keys',
    path: '/components/api-keys',
    getParentRoute: () => ExamplesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/examples/ssr': typeof ExamplesSsrRoute
  '/examples/components/api-keys': typeof ExamplesComponentsApiKeysRoute
  '/examples/components/r2-upload': typeof ExamplesComponentsR2UploadRoute
  '/examples/components/todos': typeof ExamplesComponentsTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/examples/ssr': typeof ExamplesSsrRoute
  '/examples/components/api-keys': typeof ExamplesComponentsApiKeysRoute
  '/examples/components/r2-upload': typeof ExamplesComponentsR2UploadRoute
  '/examples/components/todos': typeof ExamplesComponentsTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/examples/ssr': typeof ExamplesSsrRoute
  '/examples/components/api-keys': typeof ExamplesComponentsApiKeysRoute
  '/examples/components/r2-upload': typeof ExamplesComponentsR2UploadRoute
  '/examples/components/todos': typeof ExamplesComponentsTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples'
    | '/login'
    | '/examples/ssr'
    | '/examples/components/api-keys'
    | '/examples/components/r2-upload'
    | '/examples/components/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples'
    | '/login'
    | '/examples/ssr'
    | '/examples/components/api-keys'
    | '/examples/components/r2-upload'
    | '/examples/components/todos'
  id:
    | '__root__'
    | '/'
    | '/examples'
    | '/login'
    | '/examples/ssr'
    | '/examples/components/api-keys'
    | '/examples/components/r2-upload'
    | '/examples/components/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesRoute: typeof ExamplesRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/ssr': {
      id: '/examples/ssr'
      path: '/ssr'
      fullPath: '/examples/ssr'
      preLoaderRoute: typeof ExamplesSsrRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/components/todos': {
      id: '/examples/components/todos'
      path: '/components/todos'
      fullPath: '/examples/components/todos'
      preLoaderRoute: typeof ExamplesComponentsTodosRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/components/r2-upload': {
      id: '/examples/components/r2-upload'
      path: '/components/r2-upload'
      fullPath: '/examples/components/r2-upload'
      preLoaderRoute: typeof ExamplesComponentsR2UploadRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/components/api-keys': {
      id: '/examples/components/api-keys'
      path: '/components/api-keys'
      fullPath: '/examples/components/api-keys'
      preLoaderRoute: typeof ExamplesComponentsApiKeysRouteImport
      parentRoute: typeof ExamplesRoute
    }
  }
}

interface ExamplesRouteChildren {
  ExamplesSsrRoute: typeof ExamplesSsrRoute
  ExamplesComponentsApiKeysRoute: typeof ExamplesComponentsApiKeysRoute
  ExamplesComponentsR2UploadRoute: typeof ExamplesComponentsR2UploadRoute
  ExamplesComponentsTodosRoute: typeof ExamplesComponentsTodosRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  ExamplesSsrRoute: ExamplesSsrRoute,
  ExamplesComponentsApiKeysRoute: ExamplesComponentsApiKeysRoute,
  ExamplesComponentsR2UploadRoute: ExamplesComponentsR2UploadRoute,
  ExamplesComponentsTodosRoute: ExamplesComponentsTodosRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesRoute: ExamplesRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
