export const permissionLabels: Record<string, string> = {
  'case.view': '查看案件（相容）',
  'case.view_own': '查看自己案件',
  'case.view_all': '查看全部案件',
  'case.search': '搜尋案件',
  'case.create': '新增案件',
  'case.edit': '編輯案件',
  'case.delete': '刪除案件',
  'assignment.create': '派單',
  'assignment.reassign': '改派／解除',
  'assignment.bulk': '批量派單',
  'assignment.correct': '修正派單歷史',
  'report.view': '查看回報',
  'report.create': '新增回報',
  'report.edit': '編輯回報',
  'payment.view': '查看收款',
  'payment.create': '記錄收款',
  'payment.void': '作廢收款',
  'settlement.view': '查看回款',
  'settlement.mark_returned': '標記已回款',
  'settlement.mark_pending': '標記尚未回款',
  'finance.export': '匯出 Excel',
  'telegram_route.manage': '管理 Telegram 群組',
  'review.view': '查看待確認',
  'review.resolve': '處理待確認',
  'audit.view': '查看操作紀錄',
  'audit_log.view': '查看操作紀錄（相容）',
  'collector.manage': '管理外收人員',
  'user_permission.manage': '管理使用者與權限',
  'system_log.view': '查看系統管理日誌',
  'system_log.manage': '處理系統日誌',
  'media.view': '查看私人圖片',
  'media.upload': '上傳圖片',
  'media.delete': '刪除圖片',
  'intake.view': '查看收件',
  'intake.create': '新增收件',
  'intake.resolve': '確認收件',
  'intake.reject': '拒絕收件',
  'installment.view': '查看分期',
  'installment.create': '新增分期',
  'installment.manage': '管理分期',
  'installment.cancel': '取消分期',
};
