import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';

// Deterministic raster test fixtures: abstract document layouts, no real data.
function crc32(bytes: Uint8Array) {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++)
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function chunk(type: string, data: Buffer) {
  const name = Buffer.from(type);
  const size = Buffer.alloc(4);
  size.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([name, data])));
  return Buffer.concat([size, name, data, crc]);
}
function image(variant: number) {
  const width = 600;
  const height = 360;
  const bytes = Buffer.alloc((width * 3 + 1) * height);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let color = [241, 244, 248];
      if (x > 55 && x < 545 && y > 30 && y < 330) color = [255, 255, 255];
      if (x > 85 && x < 515 && y > 60 && y < 120)
        color = [
          [62, 87, 125],
          [81, 109, 92],
          [124, 94, 131],
        ][variant];
      if (x > 90 && x < 365 && y > 145 && y < 280 && y % 35 < 10)
        color = [214, 222, 232];
      if (x > 410 && x < 505 && y > 150 && y < 265) color = [231, 237, 244];
      const offset = y * (width * 3 + 1) + 1 + x * 3;
      bytes.set(color, offset);
    }
  }
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header[8] = 8;
  header[9] = 2;
  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    chunk('IHDR', header),
    chunk('IDAT', deflateSync(bytes)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}
const fixtures = [0, 1, 2].map((variant) => {
  const bytes = image(variant);
  return {
    base64: bytes.toString('base64'),
    sha256: createHash('sha256').update(bytes).digest('hex'),
  };
});
writeFileSync(
  new URL('../packages/db/src/demo-images.ts', import.meta.url),
  `// Generated by scripts/generate-demo-media.ts. Synthetic PNG fixtures only.\nexport const DEMO_IMAGES = ${JSON.stringify(fixtures, null, 2)} as const;\n`,
);
